version: '3'
services:
    frontend:
        build:
            context: ./test-task-sveak-frontend
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
    backend:
        build:
            context: ./test-task-sveak-backend
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
